server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://101.42.111.112:3306/student?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234@Root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO
    org.mybatis: DEBUG



